# Generated by Django 3.2.5 on 2021-11-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
