# Generated by Django 3.2.5 on 2021-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='test1', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
