# Generated by Django 3.2.5 on 2021-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certficate',
            name='certificateID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
