# Generated by Django 3.2.5 on 2021-11-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0006_alter_certficate_certificateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.client'),
        ),
    ]
